version: 2

release:
  github:
    owner: codefly-dev
    name: service-external-microsoft-sql-server

builds:
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
