name: GoReleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: codefly-dev/core/.github/workflows/go-service-release.yml@main
    with:
      setup-run: docker pull codeflydev/mssql-alembic:latest
    secrets: inherit
